publish:
  image: python:3.7-slim
  tags: [2gb, docker, kontur]
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo -n "$GIT_ROBOT_SSH_PRIVATE_KEY" | ssh-add - >/dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.skbkontur.ru >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "GIT ROBOT"
    - git init .
    - git remote -v
    - git remote remove upstream
    - git fetch origin
    - git log HEAD
    - git log $CI_COMMIT_SHA



