before_script:
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - mkdir -p $PIP_CACHE_DIR
  - pip install --requirement requirements.txt

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/
    - .venv/

publish:
  image: python:3.7-slim
  tags: [2gb, docker, kontur]
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo -n "$GIT_ROBOT_SSH_PRIVATE_KEY" | ssh-add - >/dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.skbkontur.ru >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "custom@skbkontur.ru"
    - git config --global user.name "GIT ROBOT"
    - kontur-package tag
    - kontur-package push-tags --repository-url-or-remote git@git.skbkontur.ru:${CI_PROJECT_PATH}.git



