stages:
  - test
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/
    - .venv/

before_script:
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - mkdir -p $PIP_CACHE_DIR
  - pip install --requirement requirements.txt

.test: &test
  stage: test
  tags: [2gb, docker, kontur]
  script:
    - python setup.py test
  coverage: '/\d+\%\s*$/'

test:python36:
  <<: *test
  image: python:3.6-slim

test:python37:
  <<: *test
  image: python:3.7-slim

flake8:
  stage: test
  image: python:3.7-slim
  tags: [2gb, docker, kontur]
  script:
    - pip install flake8
    - flake8

publish:
  stage: publish
  only:
    - master
  image: python:3.7-slim
  tags: [2gb, docker, kontur]
  variables:
    DIST_DIR: dist
  script:
    - echo 42
